### ISSUE TITLE
rust/tests/many_tests.rs may be flaky

### ISSUE THREAD

**Issue by G4Vi** [dylibso/observe-sdk#20]
On my machine `many.rs` never prints 250 times, usually it only print 200 times. However, it seems to work most of the time on CI.

```
test tests::integration_many ... FAILED

failures:

---- tests::integration_many stdout ----
thread 'tests::integration_many' panicked at 'assertion failed: `(left == right)`
  left: `200`,
 right: `250`', rust/tests/many_tests.rs:23:9
stack backtrace:
   0: rust_begin_unwind
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:578:5
   1: core::panicking::panic_fmt
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/panicking.rs:67:14
   2: core::panicking::assert_failed_inner
   3: core::panicking::assert_failed
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/panicking.rs:228:5
   4: many_tests::tests::integration_many
             at ./tests/many_tests.rs:23:9
   5: many_tests::tests::integration_many::{{closure}}
             at ./tests/many_tests.rs:12:30
   6: core::ops::function::FnOnce::call_once
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/ops/function.rs:250:5
   7: core::ops::function::FnOnce::call_once
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.


failures:
    tests::integration_many

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.65s

error: test failed, to rerun pass `--test many_tests`
```

**Comment by bhelx** [comment]
I "fixed" the test already here: https://github.com/dylibso/observe-sdk/blob/main/rust/tests/many_tests.rs#L44

I do think we need to look at why it's doing that though. it seemed to change even on the same machine
